# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Emanuel', :city => cities.first)

Collect::Place.create(name: "Av.  América y Colón ", address: "Av.  América y Colón ", lat: -0.196237, lng: -78.4995, city_id: 1)
Collect::Place.create(name: "Av.  América y Colón ", address: "Av.  América y Colón ", lat: -0.196237, lng: -78.4995, city_id: 1)
Collect::Place.create(name: "Av. 10 de Agosto y Ventimilla", address: "Av. 10 de Agosto y Ventimilla", lat: -0.200757, lng: -78.497, city_id: 1)
Collect::Place.create(name: "Av. 10 de Agosto y Ventimilla", address: "Av. 10 de Agosto y Ventimilla", lat: -0.200757, lng: -78.497, city_id: 1)
Collect::Place.create(name: "Av. 12 octubre y Ventimilla ", address: "Av. 12 octubre y Ventimilla ", lat: -0.208031, lng: -78.4903, city_id: 1)
Collect::Place.create(name: "Av. 12 octubre y Ventimilla ", address: "Av. 12 octubre y Ventimilla ", lat: -0.208031, lng: -78.4903, city_id: 1)
Collect::Place.create(name: "Av. 6 de Diciembre y Eloy Alfaro", address: "Av. 6 de Diciembre y Eloy Alfaro", lat: -0.186917, lng: -78.4795, city_id: 1)
Collect::Place.create(name: "Av. 6 de Diciembre y Eloy Alfaro", address: "Av. 6 de Diciembre y Eloy Alfaro", lat: -0.186917, lng: -78.4795, city_id: 1)
Collect::Place.create(name: "Av. 6 de Diciembre y Patria ", address: "Av. 6 de Diciembre y Patria ", lat: -0.208718, lng: -78.4956, city_id: 1)
Collect::Place.create(name: "Av. 6 de Diciembre y Patria ", address: "Av. 6 de Diciembre y Patria ", lat: -0.208718, lng: -78.4956, city_id: 1)
Collect::Place.create(name: "Av. 6 de Diciembre y Portugal", address: "Av. 6 de Diciembre y Portugal", lat: -0.181982, lng: -78.4789, city_id: 1)
Collect::Place.create(name: "Av. 6 de Diciembre y Portugal", address: "Av. 6 de Diciembre y Portugal", lat: -0.181982, lng: -78.4789, city_id: 1)
Collect::Place.create(name: "Av. Amazonas e Isaac Albéniz", address: "Av. Amazonas e Isaac Albéniz", lat: -0.153739, lng: -78.4879, city_id: 1)
Collect::Place.create(name: "Av. Amazonas y Av. Atahualpa", address: "Av. Amazonas y Av. Atahualpa", lat: -0.18158, lng: -78.4867, city_id: 1)
Collect::Place.create(name: "Av. Amazonas y Orellana", address: "Av. Amazonas y Orellana", lat: -0.197182, lng: -78.4898, city_id: 1)
Collect::Place.create(name: "Av. América y Av. Mariana de Jesús ", address: "Av. América y Av. Mariana de Jesús ", lat: -0.186701, lng: -78.4958, city_id: 1)
Collect::Place.create(name: "Av. América y Av. Mariana de Jesús ", address: "Av. América y Av. Mariana de Jesús ", lat: -0.186701, lng: -78.4958, city_id: 1)
Collect::Place.create(name: "Av. América y Granda Centeno", address: "Av. América y Granda Centeno", lat: -0.171219, lng: -78.4902, city_id: 1)
Collect::Place.create(name: "Av. América y Granda Centeno", address: "Av. América y Granda Centeno", lat: -0.171219, lng: -78.4902, city_id: 1)
Collect::Place.create(name: "Av. América y Villalengua", address: "Av. América y Villalengua", lat: -0.172313, lng: -78.4913, city_id: 1)
Collect::Place.create(name: "Av. América y Villalengua", address: "Av. América y Villalengua", lat: -0.172313, lng: -78.4913, city_id: 1)
Collect::Place.create(name: "Av. Amazonas y NNUU", address: "Av. Amazonas y NNUU", lat: -0.176037, lng: -78.4853, city_id: 1)
Collect::Place.create(name: "Av. Brasil y Mariano Echeverría", address: "Av. Brasil y Mariano Echeverría", lat: -0.165372, lng: -78.4894, city_id: 1)
Collect::Place.create(name: "Av. Brasil y Mariano Echeverría", address: "Av. Brasil y Mariano Echeverría", lat: -0.165372, lng: -78.4894, city_id: 1)
Collect::Place.create(name: "Av. Colón y 10 de Agosto", address: "Av. Colón y 10 de Agosto", lat: -0.198168, lng: -78.4959, city_id: 1)
Collect::Place.create(name: "Av. Colón y 10 de Agosto", address: "Av. Colón y 10 de Agosto", lat: -0.198168, lng: -78.4959, city_id: 1)
Collect::Place.create(name: "Av. Colón y 6 de Diciembre ", address: "Av. Colón y 6 de Diciembre ", lat: -0.203028, lng: -78.4873, city_id: 1)
Collect::Place.create(name: "Av. Colón y 6 de Diciembre ", address: "Av. Colón y 6 de Diciembre ", lat: -0.203028, lng: -78.4873, city_id: 1)
Collect::Place.create(name: "Av. Colón y 9 de Octubre", address: "Av. Colón y 9 de Octubre", lat: -0.198935, lng: -78.494, city_id: 1)
Collect::Place.create(name: "Av. De la Prensa y Av. Occidental ( Redondel El Condado) ", address: "Av. De la Prensa y Av. Occidental ( Redondel El Condado) ", lat: -0.102492, lng: -78.4911, city_id: 1)
Collect::Place.create(name: "Av. De la Prensa y Av. Occidental ( Redondel El Condado) ", address: "Av. De la Prensa y Av. Occidental ( Redondel El Condado) ", lat: -0.102492, lng: -78.4911, city_id: 1)
Collect::Place.create(name: "Av. de la Prensa y Carvajal", address: "Av. de la Prensa y Carvajal", lat: -0.159782, lng: -78.4879, city_id: 1)
Collect::Place.create(name: "Av. de la Prensa y Carvajal", address: "Av. de la Prensa y Carvajal", lat: -0.159782, lng: -78.4879, city_id: 1)
Collect::Place.create(name: "Av. de La Prensa y Maestro", address: "Av. de La Prensa y Maestro", lat: -0.126225, lng: -78.481, city_id: 1)
Collect::Place.create(name: "Av. de La Prensa y Maestro", address: "Av. de La Prensa y Maestro", lat: -0.126225, lng: -78.481, city_id: 1)
Collect::Place.create(name: "Av. Eloy Alfaro y Amazonas", address: "Av. Eloy Alfaro y Amazonas", lat: -0.192087, lng: -78.4887, city_id: 1)
Collect::Place.create(name: "Av. Eloy Alfaro y Amazonas", address: "Av. Eloy Alfaro y Amazonas", lat: -0.192087, lng: -78.4887, city_id: 1)
Collect::Place.create(name: "Av. Eloy Alfaro y Las Avigiras", address: "Av. Eloy Alfaro y Las Avigiras", lat: -0.137885, lng: -78.4701, city_id: 1)
Collect::Place.create(name: "Av. Eloy Alfaro y Las Avigiras", address: "Av. Eloy Alfaro y Las Avigiras", lat: -0.137885, lng: -78.4701, city_id: 1)
Collect::Place.create(name: "Av. Eloy Alfaro y Río Coca", address: "Av. Eloy Alfaro y Río Coca", lat: -0.164578, lng: -78.4682, city_id: 1)
Collect::Place.create(name: "Av. Eloy Alfaro y Río Coca", address: "Av. Eloy Alfaro y Río Coca", lat: -0.164578, lng: -78.4682, city_id: 1)
Collect::Place.create(name: "Av. General Enriquez y San Luis ", address: "Av. General Enriquez y San Luis ", lat: -0.309266, lng: -78.4523, city_id: 1)
Collect::Place.create(name: "Av. General Enriquez y San Luis ", address: "Av. General Enriquez y San Luis ", lat: -0.309266, lng: -78.4523, city_id: 1)
Collect::Place.create(name: "Av. General Rumiñahui ( ESPE) ", address: "Av. General Rumiñahui ( ESPE) ", lat: -0.315158, lng: -78.4419, city_id: 1)
Collect::Place.create(name: "Av. General Rumiñahui ( ESPE) ", address: "Av. General Rumiñahui ( ESPE) ", lat: -0.315158, lng: -78.4419, city_id: 1)
Collect::Place.create(name: "Av. General Rumiñahui y Av. Ilaló ( El triángulo) ", address: "Av. General Rumiñahui y Av. Ilaló ( El triángulo) ", lat: -0.299673, lng: -78.4593, city_id: 1)
Collect::Place.create(name: "Av. General Rumiñahui y Av. Ilaló ( El triángulo) ", address: "Av. General Rumiñahui y Av. Ilaló ( El triángulo) ", lat: -0.299673, lng: -78.4593, city_id: 1)
Collect::Place.create(name: "Av. Granados y Av. Eloy Alfaro", address: "Av. Granados y Av. Eloy Alfaro", lat: -0.165913, lng: -78.4685, city_id: 1)
Collect::Place.create(name: "Av. Granados y Av. Eloy Alfaro", address: "Av. Granados y Av. Eloy Alfaro", lat: -0.165913, lng: -78.4685, city_id: 1)
Collect::Place.create(name: "Av. Interoceánica y Juan Montalvo ( Mega Santa María de Tumbaco ) ", address: "Av. Interoceánica y Juan Montalvo ( Mega Santa María de Tumbaco ) ", lat: -0.214942, lng: -78.4063, city_id: 1)
Collect::Place.create(name: "Av. La Gasca y La Isla", address: "Av. La Gasca y La Isla", lat: -0.196598, lng: -78.502, city_id: 1)
Collect::Place.create(name: "Av. La Prensa y Tnte. Homero Salas ( Centro Comercial Aeropuerto) ", address: "Av. La Prensa y Tnte. Homero Salas ( Centro Comercial Aeropuerto) ", lat: -0.145528, lng: -78.4919, city_id: 1)
Collect::Place.create(name: "Av. La Prensa y Tnte. Homero Salas ( Centro Comercial Aeropuerto) ", address: "Av. La Prensa y Tnte. Homero Salas ( Centro Comercial Aeropuerto) ", lat: -0.145528, lng: -78.4919, city_id: 1)
Collect::Place.create(name: "Av. Maldonado (Exteriores C.C. El Recreo)", address: "Av. Maldonado (Exteriores C.C. El Recreo)", lat: -0.252255, lng: -78.5223, city_id: 1)
Collect::Place.create(name: "Av. Maldonado (Exteriores C.C. El Recreo)", address: "Av. Maldonado (Exteriores C.C. El Recreo)", lat: -0.252255, lng: -78.5223, city_id: 1)
Collect::Place.create(name: "Av. Naciones Unidas y Av. de Los Shyris", address: "Av. Naciones Unidas y Av. de Los Shyris", lat: -0.176823, lng: -78.4809, city_id: 1)
Collect::Place.create(name: "Av. Naciones Unidas y Av. de Los Shyris", address: "Av. Naciones Unidas y Av. de Los Shyris", lat: -0.176823, lng: -78.4809, city_id: 1)
Collect::Place.create(name: "Av. República y Eloy Alfaro", address: "Av. República y Eloy Alfaro", lat: -0.190953, lng: -78.4861, city_id: 1)
Collect::Place.create(name: "Av. República y Eloy Alfaro", address: "Av. República y Eloy Alfaro", lat: -0.190953, lng: -78.4861, city_id: 1)
Collect::Place.create(name: "Coruña e Isabel La Católica", address: "Coruña e Isabel La Católica", lat: -0.204757, lng: -78.4826, city_id: 1)
Collect::Place.create(name: "Coruña e Isabel La Católica", address: "Coruña e Isabel La Católica", lat: -0.204757, lng: -78.4826, city_id: 1)
Collect::Place.create(name: "Interoceánica, gasolinera Mobil", address: "Interoceánica, gasolinera Mobil", lat: -0.188933, lng: -78.4477, city_id: 1)
Collect::Place.create(name: "Interoceánica, gasolinera Mobil", address: "Interoceánica, gasolinera Mobil", lat: -0.188933, lng: -78.4477, city_id: 1)
Collect::Place.create(name: "Interoceánica, gasolinera Mobil", address: "Interoceánica, gasolinera Mobil", lat: -0.188933, lng: -78.4477, city_id: 1)
Collect::Place.create(name: "Interoceánica, gasolinera Mobil", address: "Interoceánica, gasolinera Mobil", lat: -0.188933, lng: -78.4477, city_id: 1)
Collect::Place.create(name: "Interoceánica, gasolinera Mobil", address: "Interoceánica, gasolinera Mobil", lat: -0.188933, lng: -78.4477, city_id: 1)
Collect::Place.create(name: "Intersección Las Bañistas. Cumbayá", address: "Intersección Las Bañistas. Cumbayá", lat: -0.198257, lng: -78.4375, city_id: 1)
Collect::Place.create(name: "Intersección Las Bañistas. Cumbayá", address: "Intersección Las Bañistas. Cumbayá", lat: -0.198257, lng: -78.4375, city_id: 1)
Collect::Place.create(name: "Morán Valverde y Teniente Hugo Ortiz", address: "Morán Valverde y Teniente Hugo Ortiz", lat: -0.282399, lng: -78.5438, city_id: 1)
Collect::Place.create(name: "Morán Valverde y Teniente Hugo Ortiz", address: "Morán Valverde y Teniente Hugo Ortiz", lat: -0.282399, lng: -78.5438, city_id: 1)
Collect::Place.create(name: "Parque Bicentenario", address: "Parque Bicentenario", lat: -33.3986, lng: -70.6025, city_id: 1)
Collect::Place.create(name: "Parque Bicentenario", address: "Parque Bicentenario", lat: -33.3986, lng: -70.6025, city_id: 1)
Collect::Place.create(name: "Parque Bicentenario", address: "Parque Bicentenario", lat: -33.3986, lng: -70.6025, city_id: 1)
Collect::Place.create(name: "Parque La Carolina", address: "Parque La Carolina", lat: -0.18106, lng: -78.4842, city_id: 1)
Collect::Place.create(name: "Parque La Carolina", address: "Parque La Carolina", lat: -0.18106, lng: -78.4842, city_id: 1)
Collect::Place.create(name: "Parque La Carolina", address: "Parque La Carolina", lat: -0.18106, lng: -78.4842, city_id: 1)
Collect::Place.create(name: "Peaje de los Chillos ", address: "Peaje de los Chillos ", lat: -0.243732, lng: -78.4855, city_id: 1)
Collect::Place.create(name: "Peaje de los Chillos ", address: "Peaje de los Chillos ", lat: -0.243732, lng: -78.4855, city_id: 1)
Collect::Place.create(name: "Plaza Foch", address: "Plaza Foch", lat: -0.202928, lng: -78.4911, city_id: 1)
Collect::Place.create(name: "Plaza Foch", address: "Plaza Foch", lat: -0.202928, lng: -78.4911, city_id: 1)
Collect::Place.create(name: "Plaza Foch", address: "Plaza Foch", lat: -0.202928, lng: -78.4911, city_id: 1)
Collect::Place.create(name: "Redondel de la Villaflora", address: "Redondel de la Villaflora", lat: -0.244476, lng: -78.519, city_id: 1)
Collect::Place.create(name: "Redondel de la Villaflora", address: "Redondel de la Villaflora", lat: -0.244476, lng: -78.519, city_id: 1)
Collect::Place.create(name: "Río Coca (frente a la estación de la Ecovía)", address: "Río Coca (frente a la estación de la Ecovía)", lat: -0.163738, lng: -78.4733, city_id: 1)
Collect::Place.create(name: "Río Coca (frente a la estación de la Ecovía)", address: "Río Coca (frente a la estación de la Ecovía)", lat: -0.163738, lng: -78.4733, city_id: 1)
Collect::Place.create(name: "Túnel de Guayasamín", address: "Túnel de Guayasamín", lat: -0.191863, lng: -78.474, city_id: 1)
Collect::Place.create(name: "Túnel de Guayasamín", address: "Túnel de Guayasamín", lat: -0.191863, lng: -78.474, city_id: 1)
Collect::Place.create(name: "Túnel de Guayasamín", address: "Túnel de Guayasamín", lat: -0.191863, lng: -78.474, city_id: 1)
Collect::Place.create(name: "Versalles y Fray Antonio de Marchena", address: "Versalles y Fray Antonio de Marchena", lat: -0.19957, lng: -78.499, city_id: 1)
Collect::Place.create(name: "Yaguachi y Gran Colombia", address: "Yaguachi y Gran Colombia", lat: -0.213562, lng: -78.4974, city_id: 1)
Collect::Place.create(name: "Av Mariano Acosta y Fray Vacas Galindo", address: "Av Mariano Acosta y Fray Vacas Galindo", lat: 0.348744, lng: -78.1247, city_id: 5)
Collect::Place.create(name: "Av. Teodoro Gomez y Av. Atahualpa", address: "Av. Teodoro Gomez y Av. Atahualpa", lat: 0.342113, lng: -78.1199, city_id: 5)
Collect::Place.create(name: "Av. El Retorno y Río Chinchipe", address: "Av. El Retorno y Río Chinchipe", lat: 0.33619, lng: -78.1161, city_id: 5)
Collect::Place.create(name: "Simón Bolivar y Miguel Oviedo", address: "Simón Bolivar y Miguel Oviedo", lat: 0.349796, lng: -78.1185, city_id: 5)
Collect::Place.create(name: "Panamericana Norte E35 y Corredor periferico sur", address: "Panamericana Norte E35 y Corredor periferico sur", lat: 0.336493, lng: -78.157, city_id: 5)
Collect::Place.create(name: "Panamericana Norte E35 y Dr. Luis Madera", address: "Panamericana Norte E35 y Dr. Luis Madera", lat: 0.362198, lng: -78.1119, city_id: 5)
Collect::Place.create(name: "Av Mariano Acosta y Padre Jacinto Pankery", address: "Av Mariano Acosta y Padre Jacinto Pankery", lat: 0.346465, lng: -78.1358, city_id: 5)
Collect::Place.create(name: "Av. El Retorno y Francisco Bonilla", address: "Av. El Retorno y Francisco Bonilla", lat: 0.338211, lng: -78.1157, city_id: 5)
Collect::Place.create(name: "Oviedo y Bolivar", address: "Oviedo y Bolivar", lat: 0.349839, lng: -78.1185, city_id: 5)
Collect::Place.create(name: "Av. Atahualpa y Av. Teodoro Gómez", address: "Av. Atahualpa y Av. Teodoro Gómez", lat: 0.342145, lng: -78.1198, city_id: 5)
Collect::Place.create(name: "Fray Vacas Galindo y Av. Mariano Acosta", address: "Fray Vacas Galindo y Av. Mariano Acosta", lat: 0.348771, lng: -78.1247, city_id: 5)
Collect::Place.create(name: "Juan Jose Flores y Luis Cabezas Borja", address: "Juan Jose Flores y Luis Cabezas Borja", lat: 0.351467, lng: -78.1219, city_id: 5)
Collect::Place.create(name: "Av. Francisco de Orellana y Alberto Borges. Semáforo frente a Plaza Orellana.", address: "Av. Francisco de Orellana y Alberto Borges. Semáforo frente a Plaza Orellana.", lat: -2.16501, lng: -79.896, city_id: 2)
Collect::Place.create(name: "Av. Francisco de Orellana. Semáforo esquina del CC. San Marino.", address: "Av. Francisco de Orellana. Semáforo esquina del CC. San Marino.", lat: -2.16871, lng: -79.8973, city_id: 2)
Collect::Place.create(name: "Av Francisco de Orellana y Plaza Dañín. Semáforo esquina Contraloría General del Estado.", address: "Av Francisco de Orellana y Plaza Dañín. Semáforo esquina Contraloría General del Estado.", lat: -2.17035, lng: -79.8983, city_id: 2)
Collect::Place.create(name: "Av. San Jorge y Plaza Dañin. Semáforo esquina C.C. Policentro.", address: "Av. San Jorge y Plaza Dañin. Semáforo esquina C.C. Policentro.", lat: -2.16941, lng: -79.9003, city_id: 2)
Collect::Place.create(name: "Av. Del Bombero s/n Km 6 1/2 y Av. Leopoldo Carrera. Semáforo frente a Megamaxi.", address: "Av. Del Bombero s/n Km 6 1/2 y Av. Leopoldo Carrera. Semáforo frente a Megamaxi.", lat: -2.1732, lng: -79.9404, city_id: 2)
Collect::Place.create(name: "Dr. Jose de Rubira Ramos y Ciudadela Olivos. Semáforo McDonald Ceibos.", address: "Dr. Jose de Rubira Ramos y Ciudadela Olivos. Semáforo McDonald Ceibos.", lat: -2.17606, lng: -79.9425, city_id: 2)
Collect::Place.create(name: "Víctor Emilio Estrada y las Monjas. Semáforo local Manantial.", address: "Víctor Emilio Estrada y las Monjas. Semáforo local Manantial.", lat: -2.16979, lng: -79.9098, city_id: 2)
Collect::Place.create(name: "Victor Emilio estrada y Todos los Santos 138. Semáforo frente a la Iglesia San Antonio María Claret.", address: "Victor Emilio estrada y Todos los Santos 138. Semáforo frente a la Iglesia San Antonio María Claret.", lat: -2.17335, lng: -79.9068, city_id: 2)
Collect::Place.create(name: "Av. Benjamín Carrión e Ing. Felipe Pezo. Semáforo redondel de La Rotonda.", address: "Av. Benjamín Carrión e Ing. Felipe Pezo. Semáforo redondel de La Rotonda.", lat: -2.14019, lng: -79.9087, city_id: 2)
Collect::Place.create(name: "Ing. Baquerizo Nazur y José María Egas. Semáforo KFC. Diagonal a la Iglesia Nuestra Señoa de la Alborada.", address: "Ing. Baquerizo Nazur y José María Egas. Semáforo KFC. Diagonal a la Iglesia Nuestra Señoa de la Alborada.", lat: -2.13917, lng: -79.8986, city_id: 2)
Collect::Place.create(name: "Av. Francisco de Orellana e Ing. Baquerizo Nazur. Semáforo cerca de CC. Riocentro Norte.", address: "Av. Francisco de Orellana e Ing. Baquerizo Nazur. Semáforo cerca de CC. Riocentro Norte.", lat: -2.12817, lng: -79.9061, city_id: 2)
Collect::Place.create(name: "Av. De las Américas. Semáforo M Comisariato de la Garzota.", address: "Av. De las Américas. Semáforo M Comisariato de la Garzota.", lat: -2.14518, lng: -79.8852, city_id: 2)
Collect::Place.create(name: "Av. Agustín Freire Ycaza. Semáforo Redondel frente a Mega kywi.", address: "Av. Agustín Freire Ycaza. Semáforo Redondel frente a Mega kywi.", lat: -2.142, lng: -79.8888, city_id: 2)
Collect::Place.create(name: "Av. Pedro Menéndez Gilbert y Plaza Dañín. Semáforo Parada de Metro vía Atarazana.", address: "Av. Pedro Menéndez Gilbert y Plaza Dañín. Semáforo Parada de Metro vía Atarazana.", lat: -2.17049, lng: -79.8797, city_id: 2)
Collect::Place.create(name: "Vía Daule km 4.5, Sentido 1 y 2, Semáforo Mi comisariato y Bco. Pichincha.", address: "Vía Daule km 4.5, Sentido 1 y 2, Semáforo Mi comisariato y Bco. Pichincha.", lat: -2.15894, lng: -79.9284, city_id: 2)
Collect::Place.create(name: "Av. Las aguas e Ilanes, Semáforo diagonal a la Federación Ecuatoriana de Fútbol.", address: "Av. Las aguas e Ilanes, Semáforo diagonal a la Federación Ecuatoriana de Fútbol.", lat: -2.16166, lng: -79.9116, city_id: 2)
Collect::Place.create(name: "Av. Juan Tanca Marengo y Av. Rodrigo Chávez. Semáforo intersección Gasolinera Primax y Ambacar.", address: "Av. Juan Tanca Marengo y Av. Rodrigo Chávez. Semáforo intersección Gasolinera Primax y Ambacar.", lat: -2.14763, lng: -79.906, city_id: 2)
Collect::Place.create(name: "Av. Carlos Julio Arosemena y Av. Las Monjas. Semáforo Gasolinera.", address: "Av. Carlos Julio Arosemena y Av. Las Monjas. Semáforo Gasolinera.", lat: -2.17372, lng: -79.9146, city_id: 2)
Collect::Place.create(name: "Plaza Dañin y Av. De las Américas Debajo del puente diagonal a Sombreros EcuaAndinos.", address: "Plaza Dañin y Av. De las Américas Debajo del puente diagonal a Sombreros EcuaAndinos.", lat: -2.17136, lng: -79.8916, city_id: 2)
Collect::Place.create(name: "Av.Guillermo Rolando Pareja y Agustín Freire, Garzota. Semáforo Pizza Hut y C.C. Garzocentro.", address: "Av.Guillermo Rolando Pareja y Agustín Freire, Garzota. Semáforo Pizza Hut y C.C. Garzocentro.", lat: -2.14461, lng: -79.895, city_id: 2)
Collect::Place.create(name: "Tungurahua y Av. 9 de Octubre, Semáforo esquina Pollo Gus.", address: "Tungurahua y Av. 9 de Octubre, Semáforo esquina Pollo Gus.", lat: -2.18706, lng: -79.8961, city_id: 2)
Collect::Place.create(name: "Av. Pedro Menéndez Gilbert y Av la Democracia. Semáforo esquina Junta de Calificación Militar.", address: "Av. Pedro Menéndez Gilbert y Av la Democracia. Semáforo esquina Junta de Calificación Militar.", lat: -2.17964, lng: -79.8873, city_id: 2)
Collect::Place.create(name: "Los Arcos, Samborondón. Semáforo frente a C.C. Village Plaza", address: "Los Arcos, Samborondón. Semáforo frente a C.C. Village Plaza", lat: -2.14066, lng: -79.8638, city_id: 2)
Collect::Place.create(name: "Km 1,5 Vía Samborondón. Sémaforo frente a McDonalds", address: "Km 1,5 Vía Samborondón. Sémaforo frente a McDonalds", lat: -2.14405, lng: -79.8637, city_id: 2)
Collect::Place.create(name: "Parque Samanes puerta principal", address: "Parque Samanes puerta principal", lat: -2.10185, lng: -79.9057, city_id: 2)
Collect::Place.create(name: "Peaje Vía a la Costa", address: "Peaje Vía a la Costa", lat: -2.21885, lng: -80.0847, city_id: 2)
Collect::Place.create(name: "C.C. San Marino (Puertas de entradas)", address: "C.C. San Marino (Puertas de entradas)", lat: -2.16949, lng: -79.8986, city_id: 2)
Collect::Place.create(name: "C.C. Riocentro EntreRios (Puertas de entradas)", address: "C.C. Riocentro EntreRios (Puertas de entradas)", lat: -2.14229, lng: -79.8642, city_id: 2)
Collect::Place.create(name: "C.C. Riocentro Dorado (Puertas de entradas)", address: "C.C. Riocentro Dorado (Puertas de entradas)", lat: -2.05466, lng: -79.8739, city_id: 2)
Collect::Place.create(name: "C.C. Riocentro Norte (Puertas de entradas)", address: "C.C. Riocentro Norte (Puertas de entradas)", lat: -2.12783, lng: -79.9067, city_id: 2)
Collect::Place.create(name: "C.C. Riocentro Ceibos (Puertas de entradas)", address: "C.C. Riocentro Ceibos (Puertas de entradas)", lat: -2.1767, lng: -79.9433, city_id: 2)
Collect::Place.create(name: "C.C. Mall del Sol (Puertas de entradas)", address: "C.C. Mall del Sol (Puertas de entradas)", lat: -2.1556, lng: -79.8919, city_id: 2)
Collect::Place.create(name: "C.C. City Mall (Puertas de entradas)", address: "C.C. City Mall (Puertas de entradas)", lat: -2.14039, lng: -79.9088, city_id: 2)
Collect::Place.create(name: "C.C. Policentro (Puertas de entradas)", address: "C.C. Policentro (Puertas de entradas)", lat: -2.1715, lng: -79.9001, city_id: 2)
Collect::Place.create(name: "Megamaxi Village", address: "Megamaxi Village", lat: -2.14061, lng: -79.8641, city_id: 2)
Collect::Place.create(name: "Megamaxi Mall del Sol", address: "Megamaxi Mall del Sol", lat: -2.1558, lng: -79.8916, city_id: 2)
Collect::Place.create(name: "Megamaxi City Mall", address: "Megamaxi City Mall", lat: -2.14114, lng: -79.909, city_id: 2)
Collect::Place.create(name: "Megamaxi Ceibos", address: "Megamaxi Ceibos", lat: -2.17353, lng: -79.94, city_id: 2)
Collect::Place.create(name: "Supermaxi Policentro", address: "Supermaxi Policentro", lat: -2.17013, lng: -79.9006, city_id: 2)
Collect::Place.create(name: "Yahuira Y Francisco Flor", address: "Yahuira Y Francisco Flor", lat: -1.24541, lng: -78.6309, city_id: 3)
Collect::Place.create(name: "Av. de Los Chasquis y Av. Victor Hugo", address: "Av. de Los Chasquis y Av. Victor Hugo", lat: -1.26435, lng: -78.625, city_id: 3)
Collect::Place.create(name: "Dr. Rodrigo Pachano Lalama y Mentor Mera", address: "Dr. Rodrigo Pachano Lalama y Mentor Mera", lat: -1.2294, lng: -78.6259, city_id: 3)
Collect::Place.create(name: "Av. de los Guaytambos y Delicia", address: "Av. de los Guaytambos y Delicia", lat: -1.23907, lng: -78.6343, city_id: 3)
Collect::Place.create(name: "Av. de los Guaytambos y Delicia", address: "Av. de los Guaytambos y Delicia", lat: -1.239, lng: -78.6344, city_id: 3)
Collect::Place.create(name: "Av. Pichincha y Quis Quis", address: "Av. Pichincha y Quis Quis", lat: -1.24638, lng: -78.6263, city_id: 3)
Collect::Place.create(name: "Av. Lalama y Cevallos", address: "Av. Lalama y Cevallos", lat: -1.24133, lng: -78.6266, city_id: 3)
Collect::Place.create(name: "Montalvo y Simon Bolivar", address: "Montalvo y Simon Bolivar", lat: -1.24177, lng: -78.6292, city_id: 3)
Collect::Place.create(name: "Av. Atahualpa y Victor Hugo", address: "Av. Atahualpa y Victor Hugo", lat: -1.26421, lng: -78.6275, city_id: 3)
Collect::Place.create(name: "Simón Bolívar y Francisco Flor", address: "Simón Bolívar y Francisco Flor", lat: -1.2442, lng: -78.6317, city_id: 3)
Collect::Place.create(name: "Antonio José de Sucre y Montalvo", address: "Antonio José de Sucre y Montalvo", lat: -1.24223, lng: -78.6288, city_id: 3)
Collect::Place.create(name: "Av. Cevallos y Unidad Nacional", address: "Av. Cevallos y Unidad Nacional", lat: -1.23665, lng: -78.6215, city_id: 3)
Collect::Place.create(name: "Av Cevallos y Unidad Nacional", address: "Av Cevallos y Unidad Nacional", lat: -1.23665, lng: -78.6215, city_id: 3)
Collect::Place.create(name: "Semáforo Artes", address: "Av. 12 de Octubre y Av. Don Bosco", lat: -2.91598, lng: -79.0232, city_id: 4)
Collect::Place.create(name: "Av Loja y Don Bosco", address: "Av Loja y Don Bosco", lat: -2.91355, lng: -79.0309, city_id: 4)
Collect::Place.create(name: "Av. 10 de Agosto y Ricardo Muñoz", address: "Av. 10 de Agosto y Ricardo Muñoz", lat: -2.90835, lng: -79.0168, city_id: 4)
Collect::Place.create(name: "Redondel Quinta Lucrecia", address: "Av. Primero de Mayo y Av. 12 de Octubre", lat: -2.90954, lng: -79.0192, city_id: 4)
Collect::Place.create(name: "Tres Puentes", address: "Av. Don Bosco y Av. Solano", lat: -2.91583, lng: -79.0099, city_id: 4)
Collect::Place.create(name: "Entrada principal UDA", address: "Av. 24 de Mayo y Hernan Malo", lat: -2.91817, lng: -79.0012, city_id: 4)
Collect::Place.create(name: "Garaicoa ", address: "Av. 24 de Mayo y Camino al Valle", lat: -2.9126, lng: -78.9873, city_id: 4)
Collect::Place.create(name: "Semáforo Empresa Eléctrica", address: "Av. Max Uhle y Pumapungo", lat: -2.90629, lng: -78.9838, city_id: 4)
Collect::Place.create(name: "Semáforo Monay Shopping", address: "Av. Gonzales Suarez y Rayoloma", lat: -2.89695, lng: -78.9762, city_id: 4)
Collect::Place.create(name: "Redondel Bocatti/ Gran Aki", address: "Av. Max Uhle y Av. Gonzales Suarez", lat: -2.89938, lng: -78.9847, city_id: 4)
Collect::Place.create(name: "Semáforo Cementerio", address: "Av. Gonzales Suarez y Guapondelig", lat: -2.89909, lng: -78.9907, city_id: 4)
Collect::Place.create(name: "C.C. Miraflores", address: "Elia Liut y Av. Gil Ramires Dávalos", lat: -2.88814, lng: -78.9877, city_id: 4)
Collect::Place.create(name: "Gran Colombia y Huaya Capac", address: "Gran Colombia y Huaya Capac", lat: -2.89787, lng: -78.9967, city_id: 4)
Collect::Place.create(name: "Banco Central", address: "Calle Larga y Av. Huayna Capac", lat: -2.90562, lng: -78.9966, city_id: 4)
Collect::Place.create(name: "Iglesia del Vergel / Redondel Hospital Regional", address: "Av. 12 de Abril y Av. Huayna Capac", lat: -2.91044, lng: -78.9959, city_id: 4)
Collect::Place.create(name: "Banco del Pichincha", address: "Av. 12 de Abril y Av. Solano", lat: -2.90227, lng: -79.0061, city_id: 4)
Collect::Place.create(name: "La Salle", address: "Solano y Luis Moreno Mora", lat: -2.90997, lng: -79.0082, city_id: 4)
Collect::Place.create(name: "Fybeca/ C. C. El Vergel/ Milenium", address: "Jose Peralta y Agustin Vega", lat: -2.90594, lng: -79.0024, city_id: 4)
Collect::Place.create(name: "Puente del Vado / Universidad de Cuenca", address: "Av. 12 de Abril y Av. Loja", lat: -2.89902, lng: -79.0107, city_id: 4)
Collect::Place.create(name: "Corazones", address: "Av. 12 de Abril  y Paseo 3 de Noviembre", lat: -2.89493, lng: -79.0157, city_id: 4)
Collect::Place.create(name: "Coliseo", address: "Av. 12 de Abril y Unidad Nacional", lat: -2.89534, lng: -79.0193, city_id: 4)
Collect::Place.create(name: "Redondel Totems (cambiar)", address: "Unidad Nacional y Av. Remigio Crespo", lat: -2.89778, lng: -79.0201, city_id: 4)
Collect::Place.create(name: "Ferreteria Continental", address: "Av. Remigio Crespo y Av. Loja", lat: -2.90107, lng: -79.0156, city_id: 4)
Collect::Place.create(name: "Panesa", address: "Av. Remigio Crespo y Ricardo Muñoz", lat: -2.90364, lng: -79.0138, city_id: 4)
Collect::Place.create(name: "Redondel", address: "Av. Solano y Av. Remigio Crespo", lat: -2.90633, lng: -79.0071, city_id: 4)
Collect::Place.create(name: "Parque María Auxiliadora", address: "Vega Muñoz y General Torres", lat: -2.89232, lng: -79.0061, city_id: 4)
Collect::Place.create(name: "Almacenes Chordeleg", address: "Av. Héroes de Verdeloma y Luis Cordero", lat: -2.88884, lng: -79.0025, city_id: 4)
Collect::Place.create(name: "Parque de las Américas", address: "Av. de las Américas y Av. Héroes de Verdeloma", lat: -2.88788, lng: -79.0098, city_id: 4)
Collect::Place.create(name: "Av. De las Américas y Luis Cordero", address: "Av. De las Américas y Luis Cordero", lat: -2.88457, lng: -79.0024, city_id: 4)
Collect::Place.create(name: "Punto/ Americas", address: "Av. Americas y Mariscal Lamar", lat: -2.88938, lng: -79.0223, city_id: 4)
Collect::Place.create(name: "Pío Pío", address: "Gran Colombia y Unidad Nacional", lat: -2.89202, lng: -79.0188, city_id: 4)
Collect::Place.create(name: "Parque Calderón", address: "Simon Bolivar y Benigno Malo", lat: -2.89687, lng: -79.0048, city_id: 4)
Collect::Place.create(name: "Iglesia del Cenáculo", address: "Tarqui y Bolivar", lat: -2.89604, lng: -79.0078, city_id: 4)
Collect::Place.create(name: "San Blas", address: "Bolivar y Tomas Ordoñez", lat: -2.89835, lng: -78.999, city_id: 4)
Collect::Place.create(name: "Banco del Pacífico", address: "Benigno Malo y Presidente Cordova", lat: -2.89881, lng: -79.0052, city_id: 4)
Collect::Place.create(name: "Bajada del Centenario", address: "Benigno Malo y  Calle Larga", lat: -2.90091, lng: -79.0056, city_id: 4)
Collect::Place.create(name: "Plazoleta de la Merced", address: "Calle Larga y Borrero", lat: -2.90186, lng: -79.0038, city_id: 4)
Collect::Place.create(name: "Iglesia de las Conceptas", address: "Borrero y Presidente Cordova", lat: -2.89932, lng: -79.0034, city_id: 4)

